language: cpp
compiler: gcc
language: cpp
sudo: required
dist: trusty
os: linux

branches:
  only:
    - develop
    - master

before_install:
    - echo Install dependencies
    - travis-ci/deps.sh

install:
    - echo Building INDI Core
    - travis-ci/build-core.sh 
    - travis-ci/build-3rdparty.sh
    - travis-ci/build-deb-packages.sh

script:
    - cd /home/travis/build/A-j-K/indi/build/libindi/test
    - ctest -V
    

